// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58FKY27mwER3zuCSFjcgRE7HR1VUcRWI',
    appId: '1:342116535427:web:9d9527d8662ec29f361fb6',
    messagingSenderId: '342116535427',
    projectId: 'task-manager-app-ff22',
    authDomain: 'task-manager-app-ff22.firebaseapp.com',
    storageBucket: 'task-manager-app-ff22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXf7ikBWtW9Ys2WQu7RvGym07yfSTFuUQ',
    appId: '1:342116535427:android:798b670072b69af6361fb6',
    messagingSenderId: '342116535427',
    projectId: 'task-manager-app-ff22',
    storageBucket: 'task-manager-app-ff22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_I8UtpCA4hw0WlNtKOC4WPnmTQVwQWU',
    appId: '1:342116535427:ios:2e3e437ce1c78ca4361fb6',
    messagingSenderId: '342116535427',
    projectId: 'task-manager-app-ff22',
    storageBucket: 'task-manager-app-ff22.appspot.com',
    iosBundleId: 'com.example.webAss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_I8UtpCA4hw0WlNtKOC4WPnmTQVwQWU',
    appId: '1:342116535427:ios:b4e2b8ddddac5736361fb6',
    messagingSenderId: '342116535427',
    projectId: 'task-manager-app-ff22',
    storageBucket: 'task-manager-app-ff22.appspot.com',
    iosBundleId: 'com.example.webAss.RunnerTests',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL_I8UtpCA4hw0WlNtKOC4WPnmTQVwQWU',
    authDomain: 'react-native-firebase-testing.firebaseapp.com',
    databaseURL: 'https://react-native-firebase-testing.firebaseio.com',
    projectId: 'task-manager-app-ff22',
    messagingSenderId: '342116535427',
    appId: '1:342116535427:web:9d9527d8662ec29f361fb6',
    measurementId: 'G-F79DJ0VFGS',
  );
}
